steps:
  - name: maven:3-jdk-8
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/demo/demo:$COMMIT_SHA', '.']   
  # Update Image Tags
  - id: 'Setting Init Image Tag'
    name: ubuntu
    args: ['bash','-c','sed -i "s,INIT_IMAGE_NAME,gcr.io/$PROJECT_ID/demo/demo:$COMMIT_SHA," kubernetes/deployment.yaml']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'kubernetes/deployment.yaml', '--validate=false']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east1-b'
    - 'CLOUDSDK_CONTAINER_CLUSTER=order-cluster'
images: ['gcr.io/$PROJECT_ID/demo/demo:$COMMIT_SHA']
